### ISSUE TITLE
[Mockup] Create Sell book

### ISSUE THREAD

**Issue by cgerling** [calvingerling/booktionator#12]
Page dedicated to register a new book and exchange

**Comment by cgerling** [comment]
This page has some details that should be taken into account:
* The user has 3 options to "exchange" the book:
  * Sell
  * Exchange
  * Auction
* If hasn't yet the book on system the user must register first
* If already have, then the user can improve the information about
And we have to think how the user can update the information without misrepresenting it

**Comment by diogokorok** [comment]
It's not up to the mockup to resolve such things as getting and improving info.
