### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by calvingerling** [calvingerling/booktionator#24]
This need a page to people join in. The minimal information needed is:
* Name
* Email
* Password
* Postal code
* Phone
Redirect to login when the registration is done or add the error state to the fields with invalid values.

**Comment by cgerling** [comment]
The e8a0c69bc946c67ffb07ae1f2db86e4e31ddf0da, 838692618ae48323942a20deab9bcb8852bae136, 33215c21f90fbe2dbe14e6c3d83d8cd8c2cbbbf7, f520c3fb0035c57b0b51b82fbb8d70d65b0c299e and dbb75ab296683acbd2b86cedfbc93091561fbe58 commits are related with this issue
